### ISSUE TITLE
Mailgun Question

### ISSUE THREAD

**Issue by justinallenmarsh** [robzolkos/rails-devcontainer#3]
How do you use mailgun in your devcontainer setup? Does it need to be launched by the rails app or is it an external service? I want to be able to open up mailers in development.

**Comment by robzolkos** [comment]
Yep in your development environment file set up like 

config.action_mailer.smtp_settings = {
    address: "host.docker.internal",
    port: 1025,
    domain: "host.docker.internal"
  }

You can then go to localhost:8025 and see the emails coming in.
